# Generated by Django 2.0.2 on 2018-02-11 12:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('azbakya', '0003_auto_20180210_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbook',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='userbook',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='categorybook',
            unique_together={('book', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryuser',
            unique_together={('user', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'image')},
        ),
        migrations.AlterUniqueTogether(
            name='userauthor',
            unique_together={('user', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together={('user', 'book')},
        ),
    ]
