# Generated by Django 2.0.2 on 2018-02-11 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('azbakya', '0004_auto_20180211_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookWish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='user',
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ManyToManyField(through='azbakya.UserBookRate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserBook',
        ),
        migrations.AddField(
            model_name='userbookwish',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azbakya.Book'),
        ),
        migrations.AddField(
            model_name='userbookwish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbookread',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azbakya.Book'),
        ),
        migrations.AddField(
            model_name='userbookread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbookrate',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azbakya.Book'),
        ),
        migrations.AddField(
            model_name='userbookrate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userbookwish',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='userbookread',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='userbookrate',
            unique_together={('user', 'book')},
        ),
    ]
