# Generated by Django 2.0.2 on 2018-02-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azbakya', '0005_auto_20180211_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookread',
            name='read',
        ),
        migrations.RemoveField(
            model_name='userbookwish',
            name='wishlist',
        ),
    ]
